### ISSUE TITLE
 Experiment time

### ISSUE THREAD

**Issue by starIdeasLabs** [LuminLiu/HierFL#7]
Hi ，Mr. Liu,
First of all, thanks for sharing the code, I was very successful when I reproduced the experiment, but I was not very satisfied with the time of the experiment. Here are two of my questions, I hope to get your help.
(1) I use a CPU, and the experimental results found that the more times I interact with the edge server, the more time it will take, which is not very consistent with your experimental results, is it that I am using a CPU instead of a GPU? 
(2) Also, it's not quite clear that parallelism doesn't seem to be used in the code.
Thank you for helping me answer my questions, and I wish you success and happiness every day.

**Comment by LuminLiu** [comment]
Hi, you are right. The codes are executed sequentially instead of in parallel, but the code logic is unaffected though. Thus, the CPU/GPU runtime is not the training time of an actual FL system. If you want to calculate the FL training time, you need to assume the communication and computation delays and then calculate it with hand.
